<?php

namespace Database\Seeders;

use App\Models\Blog;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BlogSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $blogs = [
            [
                'title' => 'Mastering Laravel for Modern Web Development',
                'author_name' => 'John Carter',
                'slug' => 'mastering-laravel-for-modern-web-development',
                'excerpt' => 'A complete guide to understanding Laravel’s structure, tools, and workflows for better development.',
                'content' => 'Laravel is one of the most powerful PHP frameworks. It offers elegant syntax, powerful tools, and an amazing ecosystem. In this article, we explore routing, Eloquent ORM, middleware, and Blade templating.',
                'featured_image' => 'profile_pictures/photo1.jpg',
                'featured_image_url' => null,
                'image_url' => null,
                'author_id' => 1,
                'category' => 'Web Development',
                'tags' => json_encode(['Laravel', 'PHP', 'Backend']),
                'is_published' => true,
                'published_at' => now(),
                'views' => 120,
                'meta_title' => 'Mastering Laravel for Modern Web Development',
                'meta_description' => 'Learn Laravel from basics to advanced techniques.',
                'meta_keywords' => 'Laravel, PHP, Web Development',
                'order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Building Fast APIs Using Node.js',
                'author_name' => 'Sarah Mitchell',
                'slug' => 'building-fast-apis-using-nodejs',
                'excerpt' => 'Node.js enables developers to build high-performance APIs with ease and speed.',
                'content' => 'Node.js provides a non-blocking architecture that makes API-building extremely efficient. In this guide, we cover Express.js, routing logic, middleware, and deploying lightweight applications.',
                'featured_image' => 'profile_pictures/photo2.jpg',
                'featured_image_url' => null,
                'image_url' => null,
                'author_id' => 3,
                'category' => 'Backend',
                'tags' => json_encode(['Node.js', 'API', 'JavaScript']),
                'is_published' => true,
                'published_at' => now(),
                'views' => 95,
                'meta_title' => 'Building Fast APIs Using Node.js',
                'meta_description' => 'Discover how to build scalable APIs using Node.js.',
                'meta_keywords' => 'Node.js, API, Express.js',
                'order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'UI/UX Principles Every Developer Should Know',
                'author_name' => 'Lucas Hern',
                'slug' => 'ui-ux-principles-every-developer-should-know',
                'excerpt' => 'Understanding UI/UX fundamentals can significantly improve user experience.',
                'content' => 'Good design goes far beyond visuals. Developers should understand spacing, contrast, hierarchy, accessibility, and the psychology behind user actions. This article breaks down common UI/UX rules.',
                'featured_image' => 'profile_pictures/photo3.jpg',
                'featured_image_url' => null,
                'image_url' => null,
                'author_id' => 2,
                'category' => 'Design',
                'tags' => json_encode(['UI', 'UX', 'Design']),
                'is_published' => false,
                'published_at' => null,
                'views' => 30,
                'meta_title' => 'UI/UX Principles for Developers',
                'meta_description' => 'Learn the main UI and UX concepts.',
                'meta_keywords' => 'UI, UX, Web Design',
                'order' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Why React Remains the King of Frontend Development',
                'author_name' => 'Emily Ross',
                'slug' => 'why-react-remains-the-king-of-frontend-development',
                'excerpt' => 'Despite many competitors, React continues to dominate frontend development.',
                'content' => 'React’s component-based architecture, virtual DOM, strong ecosystem, and huge community keep it at the top. This article explores performance benefits, developer experience, and industry adoption.',
                'featured_image' => 'profile_pictures/photo4.jpg',
                'featured_image_url' => null,
                'image_url' => null,
                'author_id' => 5,
                'category' => 'Frontend',
                'tags' => json_encode(['React', 'JavaScript', 'Frontend']),
                'is_published' => true,
                'published_at' => now(),
                'views' => 210,
                'meta_title' => 'Why React Dominates Frontend Development',
                'meta_description' => 'A deep dive into React’s popularity and strengths.',
                'meta_keywords' => 'React, JavaScript, Frontend',
                'order' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Future of AI in Software Engineering',
                'author_name' => 'Aiden Clarke',
                'slug' => 'the-future-of-ai-in-software-engineering',
                'excerpt' => 'AI is reshaping how developers design, code, test, and deploy applications.',
                'content' => 'Artificial intelligence is rapidly transforming software development. Code assistants, automation tools, predictive algorithms, and AI-driven testing are becoming standard in engineering workflows.',
                'featured_image' => 'profile_pictures/photo1.jpg',
                'featured_image_url' => null,
                'image_url' => null,
                'author_id' => 4,
                'category' => 'Technology',
                'tags' => json_encode(['AI', 'Machine Learning', 'Tech Future']),
                'is_published' => true,
                'published_at' => now(),
                'views' => 180,
                'meta_title' => 'AI Impact on Software Engineering',
                'meta_description' => 'How AI will influence development in the coming years.',
                'meta_keywords' => 'AI, Software Engineering',
                'order' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Effective Debugging Techniques for Beginners',
                'author_name' => 'Mia Thompson',
                'slug' => 'effective-debugging-techniques-for-beginners',
                'excerpt' => 'Debugging is a skill every developer must master — here’s how to get started.',
                'content' => 'From console logging to breakpoints and unit testing, debugging requires a structured mindset. This article covers practical techniques used by professionals to track and fix bugs efficiently.',
                'featured_image' => 'profile_pictures/photo3.jpg',
                'featured_image_url' => null,
                'image_url' => null,
                'author_id' => 7,
                'category' => 'Programming',
                'tags' => json_encode(['Debugging', 'Coding', 'Beginners']),
                'is_published' => false,
                'published_at' => null,
                'views' => 15,
                'meta_title' => 'Debugging Tips for New Developers',
                'meta_description' => 'Learn simple and practical debugging strategies.',
                'meta_keywords' => 'Debugging, Programming, Coding',
                'order' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];
        Blog::insert($blogs);
    }
}
