<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => 'Ultratek Pro Headphones',
                'category' => 'Electronics',
                'price' => 149.99,
                'sku' => 'UTK-HP-001',
                'highlights' => 'High-quality sound, Noise cancelling, 30-hour battery life',
                'description' => 'Premium wireless headphones with deep bass and comfortable over-ear design.',
                'rating' => 4.5,
                'image' => 'profile_pictures/photo1.jpg',
                'image_url' => null,
                'is_featured' => true,
                'is_active' => true,
                'order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Aurelian Smartwatch X',
                'category' => 'Wearables',
                'price' => 199.90,
                'sku' => 'ARL-SW-002',
                'highlights' => 'Heart rate tracking, AMOLED display, Waterproof',
                'description' => 'A next-gen smartwatch with powerful health tracking and customizable watch faces.',
                'rating' => 4.3,
                'image' => 'profile_pictures/photo2.jpg',
                'image_url' => null,
                'is_featured' => false,
                'is_active' => true,
                'order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nimbus Wireless Keyboard',
                'category' => 'Accessories',
                'price' => 59.50,
                'sku' => 'NMB-KB-003',
                'highlights' => 'Silent keys, Ultra-slim, Long battery life',
                'description' => 'Compact wireless keyboard offering smooth typing and durable build.',
                'rating' => 4.2,
                'image' => 'profile_pictures/photo3.jpg',
                'image_url' => null,
                'is_featured' => false,
                'is_active' => true,
                'order' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Solara Portable Speaker',
                'category' => 'Audio',
                'price' => 89.00,
                'sku' => 'SLR-SP-004',
                'highlights' => 'Water-resistant, Deep bass, Bluetooth 5.0',
                'description' => 'Compact and powerful portable speaker perfect for indoor and outdoor use.',
                'rating' => 4.6,
                'image' => 'profile_pictures/photo4.jpg',
                'image_url' => null,
                'is_featured' => true,
                'is_active' => true,
                'order' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Aerion Gaming Mouse',
                'category' => 'Accessories',
                'price' => 39.99,
                'sku' => 'AER-GM-005',
                'highlights' => 'RGB lighting, 6 customizable buttons, Ergonomic grip',
                'description' => 'A precision gaming mouse built for speed, accuracy, and comfort during long sessions.',
                'rating' => 4.4,
                'image' => 'profile_pictures/photo2.jpg',
                'image_url' => null,
                'is_featured' => false,
                'is_active' => true,
                'order' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Zenith 4K Action Camera',
                'category' => 'Photography',
                'price' => 129.90,
                'sku' => 'ZTH-CM-006',
                'highlights' => '4K recording, Waterproof case, Wide-angle lens',
                'description' => 'Capture every adventure in high resolution with stabilization and wide field of view.',
                'rating' => 4.1,
                'image' => 'profile_pictures/photo1.jpg',
                'image_url' => null,
                'is_featured' => true,
                'is_active' => true,
                'order' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nebula LED Desk Lamp',
                'category' => 'Home & Office',
                'price' => 24.50,
                'sku' => 'NBL-LP-007',
                'highlights' => 'Touch controls, Adjustable brightness, Eye-care technology',
                'description' => 'A modern LED desk lamp designed to reduce eye strain and enhance workspace lighting.',
                'rating' => 4.0,
                'image' => 'profile_pictures/photo3.jpg',
                'image_url' => null,
                'is_featured' => false,
                'is_active' => true,
                'order' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Vortex Mini Bluetooth Speaker',
                'category' => 'Audio',
                'price' => 34.99,
                'sku' => 'VTX-SP-008',
                'highlights' => 'Surround sound, Compact size, Long battery life',
                'description' => 'A pocket-sized speaker with powerful audio performance and smooth Bluetooth connectivity.',
                'rating' => 4.3,
                'image' => 'profile_pictures/photo4.jpg',
                'image_url' => null,
                'is_featured' => false,
                'is_active' => true,
                'order' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Glacier Stainless Steel Bottle',
                'category' => 'Outdoors',
                'price' => 19.99,
                'sku' => 'GLC-BT-009',
                'highlights' => 'Insulated, 24-hour cold retention, Leakproof lid',
                'description' => 'Durable insulated bottle perfect for travel, gym use, and outdoor adventures.',
                'rating' => 4.5,
                'image' => 'profile_pictures/photo1.jpg',
                'image_url' => null,
                'is_featured' => true,
                'is_active' => true,
                'order' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        Product::insert($products);
    }
}
